### ISSUE TITLE
What is the version of tensorflow?

### ISSUE THREAD

**Issue by AIshouldbecry** [ChihChiangHuang/AlbionFishingBot#2]

**Comment by ChihChiangHuang** [comment]
![image](https://user-images.githubusercontent.com/48548508/99139652-c4d11d00-2675-11eb-91e7-00cec0aa39b6.png)

**Comment by AIshouldbecry** [comment]
Is it the tensorflow-GPU version？

**Comment by AIshouldbecry** [comment]
![image](https://user-images.githubusercontent.com/34427864/99139789-bf52e300-2633-11eb-9067-dc85d5364917.png)
It seems to be a problem with my sample set。

**Comment by ChihChiangHuang** [comment]
This is probably related to keras. My keras version is 2.4.3. However, if you still got this problem, I suggest you uninstall your python, reinstall python 3.8 64 bits version, and install all the packages once again as mentioned in the readme description.

**Comment by AIshouldbecry** [comment]
May it be related to the main script? Main.py seem to get the frist model.Even if I enable  enable_NN,i still cant get model.

**Comment by ChihChiangHuang** [comment]
1. Regarding build your own model with ANN_build.py. You should run the main.py for a long time to collect enough data for building Machine Learning Model.


2. The original code enable the Neural Network. Search the variable, enable_NN, and set to False if you do not have the NN model. Or you can find my model in the release. But my model will not be the best model for your PC
