### ISSUE TITLE
I try Run Main.py and got this issue

### ISSUE THREAD

**Issue by Pali1231** [ChihChiangHuang/AlbionFishingBot#6]
2020-11-19 00:26:01.663851: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
Anaconda Prompt (miniconda3) - main.py
Traceback (most recent call last):
  File "C:\Users\Pali\AppData\Local\Programs\Python\Python37\Main.py", line 58, in <module>
    NN_model = load_model('NN_model')
  File "C:\Users\Pali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\saving\save.py", line 186, in load_model
    loader_impl.parse_saved_model(filepath)
  File "C:\Users\Pali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 113, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: NN_model/{saved_model.pbtxt|saved_model.pb}

**Comment by ChihChiangHuang** [comment]
Please read the "Readme.md"

If you do not have an ANN model with you, please run the main script without enabled ANN in the branch. It will collect the data when fishing. You can further use these data to train your own model. The ANN involvement would improve the overall performance by filtering out the footsteps from other players and the noise made by the monsters. You can also find my own NN_model from the release. However, the model is fit to my own PC and may not be suitable for you.

**Comment by Pali1231** [comment]
My mistake. Now the script run but after first cast got error massage.
(position -1: os error3 ) after work send full massege. I'm littary starter in python. Can you help me in discord or anywhere?

**Comment by ChihChiangHuang** [comment]
I cannot do python tutorial for you. If the problem is a general Python problem, please search the problem on StackOverflow or somewhere else. However, if the problem is directly related to my program, you can ask here, and provide sufficient information.

so first, what operating system you are using?
did you find the correct audio instrument?

**Comment by Pali1231** [comment]
I use windows 10. Yes i found becouse only once work well the script. Cast rod, detect sound and catch out the fish.

**Comment by ChihChiangHuang** [comment]
Post the entire error message

**Comment by Pali1231** [comment]
Traceback (most recent call last):
  File "C:\Users\geri-\Desktop\AlbionFishingBot-main\Main.py", line 273, in <module>
    np.save(time.strftime("data/succ_%Y%m%d-%H%M%S"),data_new)  # data collecting used for ANN
  File "<__array_function__ internals>", line 5, in save
  File "C:\Users\geri-\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\lib\npyio.py", line 541, in save
    fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/succ_20201120-100906.npy'

catch out 1 fish well and after stop and got this massage

**Comment by ChihChiangHuang** [comment]
So this is a general Python question. You should try to google this question.

FileNotFoundError: [Errno 2] No such file or directory: 'data/succ_20201120-100906.npy'
which happens on the line, np.save(time.strftime("data/succ_%Y%m%d-%H%M%S"),data_new)

The program tries to save a file to a folder called data. But there is not a dictionary called data.

So the solution is to create a folder named data
![image](https://user-images.githubusercontent.com/48548508/99782539-416f6a00-2b54-11eb-8c03-ace517260939.png)

**Comment by Pali1231** [comment]
Finally work. thans you. but this only work if you put close microphone to the headset?

**Comment by ChihChiangHuang** [comment]
Wow, I never thought that people using this method.

So, what we need to do is sending the speaker audio to microphone. There is a mode for microphone called stereo mix. Google "stereo mix windows 10" to study how to switch to this mode on your PC settings. And then the audio from the speaker should be also passed to the microphone.

**Comment by Pali1231** [comment]
Thx for everything. my last question this is eat fishing bait? can you tell me details? eat after 10 catch or how?
