### ISSUE TITLE
So umm..

### ISSUE THREAD

**Issue by Dhanamerdeka** [ChihChiangHuang/AlbionFishingBot#7]
So... you won't want to create executable for windows?
my brain is not enough for understanding this

**Comment by ChihChiangHuang** [comment]
You can find the packed program in the release now. The version is non-ML-involved and easier to use. That's all I can provide.

If you want to have better performance, machine learning can improve the performance by filtering out the footsteps from monsters and noise from other players. However, you need to get the ANN model.
